id: A2617BC92
title: A Song of Calling the Guru from Afar
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:15:46.113597
  last_modified_at: 2022-02-28 23:15:46.113605
